FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake python-is-python3 python3-pip libblas-dev liblapack-dev
RUN pip3 install conan

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8
